### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by blackspikeltd** [musocrat/jquery-video-lightning#14]
Is it just me or does this not work in Safari? Works great in Chrome and FF. Thanks!

**Comment by musocrat** [comment]
Ewww, that's no good. I tried it in browserling and ran into an undefined error with one of the elements. I'm going to try to get access to an OSX environment and I'll get this debugged. I'll let you know what I come up with.

**Comment by blackspikeltd** [comment]
I should have added the error:
[Error] TypeError: undefined is not a function (evaluating 'this.el.getAttribute("data-video-" + k)')
Line 121
Cheers!

**Comment by pax** [comment]
It works for me in Safari 8.0.8 (10600.8.9)

**Comment by blackspikeltd** [comment]
Hmm that's odd, does it work on my site (click the red play button)? - it doesn't work in my Safari desktop 8.0.8 http://djcheeba.com/site/

**Comment by pax** [comment]
No, there it doesn't work.

**Comment by musocrat** [comment]
Sorry for the delay, just finished up a massive project at work. Just now getting time to look at this. Getting some Hackintosh action going now. Hopefully this will be resolved very soon.

**Comment by musocrat** [comment]
Man, I'm really sorry for my delay. Hackintosh on a VM was a no go for me. Finally broke down and borrowed a macbook from work. It should be fixed now. If you want to update to 3.0.6 and let me know if that takes care of it for you.

**Comment by musocrat** [comment]
I'm going to go ahead and close this, but let me know if you have any more troubles with it.

**Comment by blackspikeltd** [comment]
Hey dude geez no need to apologise! Thank you so much for the fix I just tried it on [my site](http://djcheeba.com/about/) and it works great. We're super grateful.
